### ISSUE TITLE
どうするアイフル

### ISSUE THREAD

**Issue by tera3939** [azyobuzin/ConsoleCalculator#1]
（演習）条件分岐２のフローチャートをExcelで作成し，pdfで保存して提出せよ．なお，複数問題により，複数シートとなるが，エクスポートする際に「オプション」の「ブック全体」を選ぶと，複数シートが１つのpdfファイルとなる．これは発展演習であり必須ではない．
＿人人人人人人人人人人人人人人人人人人人人＿
＞　条件分岐２のフローチャートをExcelで作成　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣

**Comment by azyobuzin** [comment]
ほんとそれ

**Comment by tera3939** [comment]
やれよ？

**Comment by azyobuzin** [comment]
マジ突然の死じゃん

**Comment by tera3939** [comment]
頑張って死のうな

**Comment by azyobuzin** [comment]
![心が折れた音](https://cloud.githubusercontent.com/assets/1000655/15641656/5df1d5a4-267d-11e6-922e-1553248cfbf4.png)

**Comment by tera3939** [comment]
githubはチャットツールではない

**Comment by azyobuzin** [comment]
gitter ルーム作るか？？

**Comment by tera3939** [comment]
なにそれしらない

**Comment by azyobuzin** [comment]
じゃあslack

**Comment by tera3939** [comment]
slackなら使ったことある！！(よくわかってない)

**Comment by azyobuzin** [comment]
飽きたな

**Comment by tera3939** [comment]
わかる
